### ISSUE TITLE
Błąd SSL na kompilacji snapshot openwrt

### ISSUE THREAD

**Issue by kuncy7** [4IceG/Modem-extras#2]
Cześć,
Jak próbuję dodać Twoje repozytorium na mojej kompilacji (snapshot) dostaję taki błąd:
```
root@OpenWrt:~# wget https://github.com/4IceG/Modem-extras/raw/main/myrepo/IceG-repo.pub -O /tmp/IceG-repo.pub
Downloading 'https://github.com/4IceG/Modem-extras/raw/main/myrepo/IceG-repo.pub'
Connecting to 140.82.121.3:443
Redirected to /4IceG/Modem-extras/main/myrepo/IceG-repo.pub on raw.githubusercontent.com
SSL error: SSL - Bad input parameters to function
Connection error: Connection failed
root@OpenWrt:~# 
```
Po zainstalowaniu pełnego wget-ssl , błąd znika i repozytorium się dodaje.

**Comment by 4IceG** [comment]
Siemanko,
Kolego @kuncy7 przecież repozytorium działa (jak sam to napisałeś), więc nie mam co tu naprawiać.
Strzelam, że jakbyś dodał do linku powyżej parametr `wget --no-check-certificate..` to mogłoby się też pobrać bez `SSL error`.

**Comment by davidohne** [comment]
--no-check-certificate works when adding the repository but opkg update is still broken then. My solution is at the moment to install wget-ssl before. Then everything works as expected. 

`opkg install wget-ssl`

**Comment by kuncy7** [comment]
Wiadomo że wget-ssl rozwiązuje problem.
Dziwne jest dla mnie tylko to że bez niego (wget-ssl) repozytoria openwrt czytają się prawidłowo, a Twoje mają ten błąd.
Może openwrt jakoś inaczej (inne biblioteki SSL) generuje certyfikaty, stąd ten: " Bad input parameters to function" ??

**Comment by 4IceG** [comment]
Szukając rozwiązania/wyjaśnienia natrafiłem na ten wątek https://github.com/openwrt/openwrt/issues/15427 oraz https://github.com/openwrt/uclient/issues/4.

**Comment by kuncy7** [comment]
Właśnie wgrałem na majego AW1000 najnowszy snapshot nss od @qosmio tyle że skompilowany z biblioteką openssl
i z nią ten problem nie występuję. Twoje repozytorium dodało się bez problemu.

**Comment by 4IceG** [comment]
> Czyli to (chyba) nie problem klienta, a biblioteki której używa.

Na to wygląda. Ilu użytkowników, tyle wariacji konfiguracji.

_Repo działa, więc może ktoś z niego skorzysta._

**Comment by kuncy7** [comment]
To mamy wyjaśnione, dziękuję. Zamykam zgłoszenie

**Comment by MiG-41** [comment]
A ja przed chwilą wgrałem do mojego aw1000 fw od [AgustinLorenz](https://github.com/AgustinLorenzo) i tam jest błąd SSL...
`root@OpenWrt:~# wget https://github.com/4IceG/Modem-extras/raw/main/myrepo/IceG-repo.pub -O /tmp/IceG-repo.pub
Downloading 'https://github.com/4IceG/Modem-extras/raw/main/myrepo/IceG-repo.pub'
Connecting to 140.82.121.4:443
Redirected to /4IceG/Modem-extras/main/myrepo/IceG-repo.pub on raw.githubusercontent.com
SSL error: SSL - Bad input parameters to function
Connection error: Connection failed
root@OpenWrt:~# `
