### ISSUE TITLE
sms-tools not receiving messages

### ISSUE THREAD

**Issue by ArSd-g** [4IceG/Modem-extras#3]
Hi can't get messages to be received, sending works!
Any clue?

![20240705_014745](https://github.com/4IceG/Modem-extras/assets/42816950/24d17351-9f53-4d13-879b-4cadecb5ccc4)

**Comment by 4IceG** [comment]
Hi @ArSd-g ,
Have you checked whether SMS are visible from console?

**Comment by ArSd-g** [comment]
Working wrong settings reading sms from modem instead of sim.

**Comment by ArSd-g** [comment]
Working! wrong settings reading sms from modem instead of sim. sorry!
